SELECT NOE.SEBT_IEESRecordID AS SUBSCRIBERKEY,
NOE.EMAIL AS EMAILADDRESS,
MIN(DATEJOINED) AS DATEJOINED

FROM SEBT_Phase2_NOE_Daily_Send_Applicants NOE
LEFT JOIN _SUBSCRIBERS S
ON NOE.SEBT_IEESRecordID = S.SUBSCRIBERKEY

GROUP BY NOE.SEBT_IEESRecordID, NOE.EMAIL