SELECT NOE.HOHINDIVIDUALID AS SUBSCRIBERKEY,
NOE.EMAIL AS EMAILADDRESS,
MIN(DATEJOINED) AS DATEJOINED

FROM SEBT_PHASE1_DAILY_SEND_DIRECTLY_CERTIFIED NOE
LEFT JOIN _SUBSCRIBERS S
ON NOE.HOHINDIVIDUALID = S.SUBSCRIBERKEY

GROUP BY NOE.HOHINDIVIDUALID, NOE.EMAIL