SELECT S.EMAILADDRESS,
COUNT(DISTINCT C.SUBSCRIBERKEY) AS CONTACTCOUNT

FROM ALL_CONTACTS_MIRROR_DE C
LEFT JOIN _SUBSCRIBERS S
ON C.SUBSCRIBERKEY = S.SUBSCRIBERKEY

WHERE C.SUBSCRIBERKEY IS NOT NULL
GROUP BY EMAILADDRESS