SELECT RFI.DATEADDEDTOTHEJOURNEY,
    RFI.TYPEOFASSISTANCE,
    RFI.CONTACTID,
    RFI.EMAIL,
    RFI.PREFERREDCONTACTMETHODCODE,
    RFI.SECONDDUEDATENUDGE,
    RFI.COUNT_VCLDESCRIPTION,
    RFI.TODAY_DATE,
    RFI.VALIDSOURCERECEIVEDDATE,
    RFI.INDIVIDUALID,
    RFI.ISHEADOFHOUSEHOLD,
    RFI.COUNT_VCLDESCRIPTIONES,
    RFI.IS_VERIFICATION_COMPLETED,
    RFI.ISINSUFFICIENT,
    RFI.PROGRAMCODE,
    RFI.LANGUAGEPREFERENCE,
    RFI.THIRDDUEDATENUDGE,
    RFI.REJECTIONDATE,
    RFI.ISEXTENDED,
    RFI.DROPDOWN_COMMENTS,
    RFI.LASTNAME,
    RFI.CASENUMBER,
    RFI.VERIFICATIONCHECKLISTDUEDATE,
    RFI.FIRSTDUEDATENUDGE,
    RFI.IS_CHECKLIST_DUE_DATE_EXPIRED,
    RFI.FIRSTNAME,
    RFI.PRIMARYPHONENUMBER,
    RFI.FOURTHDUEDATENUDGE,
    RFI.LOCALE,
    NEWID() AS GUID

FROM RFI_REMINDERS_ENTRY_DE RFI
LEFT JOIN _SENT S ON S.SUBSCRIBERKEY = RFI.INDIVIDUALID
LEFT JOIN _JOB J ON S.JOBID = J.JOBID
WHERE DATEDIFF(D,RFI.TODAY_DATE, S.EVENTDATE) = 0
AND J.EMAILID IN ('101121', '101122') OR
J. EMAILID IS NULL
