SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'LANGUAGEPREFERENCE' AS INVALIDFIELD,
LANGUAGEPREFERENCE AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE LANGUAGEPREFERENCE IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'SEPREASON' AS INVALIDFIELD,
SEPREASON AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE SEPREASON IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'SEPREASON' AS INVALIDFIELD,
SEPREASON AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE LEN(SEPREASON) > 250

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'TYPEOFPROOF' AS INVALIDFIELD,
TYPEOFPROOF AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE TYPEOFPROOF IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'TYPEOFPROOF' AS INVALIDFIELD,
TYPEOFPROOF AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE LEN(TYPEOFPROOF) > 250

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'TYPEOFPROOF_SPANISH' AS INVALIDFIELD,
TYPEOFPROOF_SPANISH AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE TYPEOFPROOF_SPANISH IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'TYPEOFPROOF_SPANISH' AS INVALIDFIELD,
TYPEOFPROOF_SPANISH AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE LEN(TYPEOFPROOF_SPANISH) > 250

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'SEPREASON_SPANISH' AS INVALIDFIELD,
SEPREASON_SPANISH AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE SEPREASON_SPANISH IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'SEPREASON_SPANISH' AS INVALIDFIELD,
SEPREASON_SPANISH AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE LEN(SEPREASON_SPANISH) > 250

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'INITIAL_NUDGEDATE' AS INVALIDFIELD,
CAST(INITIAL_NUDGEDATE AS VARCHAR) AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE INITIAL_NUDGEDATE IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'SECOND_NUDGEDATE' AS INVALIDFIELD,
CAST(SECOND_NUDGEDATE AS VARCHAR) AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE SECOND_NUDGEDATE IS NULL

UNION ALL

SELECT HOHINDIVIDUALID AS SUBSCRIBERKEY,
'THIRD_NUDGEDATE' AS INVALIDFIELD,
CAST(THIRD_NUDGEDATE AS VARCHAR) AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM CR2052_SVI_ENTRY_IMPORT_INITIAL
WHERE THIRD_NUDGEDATE IS NULL