SELECT A.PROGRAMCODE,
A.CASENUMBER,
A.PRIMARYPHONENUMBER,
A.EMAIL,
A.LANGUAGEPREFERENCE,
A.PREFERREDNOTIFICATIONMETHOD,
A.TYPEOFASSISTANCE,
A.SEPREASON,
A.SVICREATEDDATE,
A.TYPEOFPROOF,
A.SVISTATUSCODE,
CAST(A.SVIDUEDATE AS DATE) AS SVIDUEDATE,
A.SEPVRFTASKSTATUS,
B.TYPEOFPROOF_SPANISH,
A.SEPREASON_SPANISH,
A.INITIAL_NUDGEDATE,	
A.SECOND_NUDGEDATE,	
A.THIRD_NUDGEDATE,
A.FOURTH_NUDGEDATE,	
A.ISHEADOFHOUSEHOLD,	
A.HOHINDIVIDUALID,
A.IMPORTDATE,
A.LOCALE,
A.SEPISINSUFFICIENT,
CASE WHEN A.LANGUAGEPREFERENCE = 'SPANISH' THEN /* IF THE LANGUAGE PREFERENCE IS SPANISH, USE THE SPANISH TYPEOFPROOF */
  B.SEPDROPDOWN_COMMENTS
ELSE 
  A.SEPDROPDOWN_COMMENTS
END AS SEPDROPDOWN_COMMENTS,
A.SEPREJECTIONDATE,
A.SEPISEXTENDED

FROM TEST_SVI_ENTRY_TYPEOFPROOFENGLISH A /* FROM THE ENGLISH TYPEOFPROOF TABLE */
LEFT JOIN TEST_SVI_ENTRY_TYPEOFPROOFSPANISH B /* JOIN WITH THE SPANISH TYPEOFPROOF TABLE FOR SPANISH ONLY VALUES */
ON A.HOHINDIVIDUALID = B.HOHINDIVIDUALID