SELECT EMAIL,
CASENUMBER,
PROGRAMCODE,
TYPEOFASSISTANCE,
ISHEADOFHOUSEHOLD,
INITIAL_NUDGEDATE,
SECOND_NUDGEDATE,
THIRD_NUDGEDATE,
FOURTH_NUDGEDATE,
SVISTATUSCODE,
SEPVRFTASKSTATUS,
SEPREASON,
TRIM(PREFERREDNOTIFICATIONMETHOD) AS PREFERREDNOTIFICATIONMETHOD,
SVICREATEDDATE,
SVIDUEDATE,
HOHINDIVIDUALID,
/* FORMATS THE PHONE NUMBER IN 11 CHARACTER STRING */
CASE
    WHEN LEN(PRIMARYPHONENUMBER) >= 10 THEN 
    CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(PRIMARYPHONENUMBER),':',''),'-',''),'(',''),')',''),10))
    ELSE NULL
END AS PRIMARYPHONENUMBER,
LANGUAGEPREFERENCE,
TYPEOFPROOF_SPANISH,
SEPREASON_SPANISH,
TYPEOFPROOF,
IMPORTDATE,
SEPISINSUFFICIENT,
SEPDROPDOWN_COMMENTS,
SEPREJECTIONDATE,
SEPISEXTENDED

FROM TEST_SVI_ENTRY_IMPORT_DE /* FRFOM THE FINAL TEST SVI ENTRY IMPORT DE TABLE */
WHERE 
    PROGRAMCODE = 'QP' /* FILTERING FOR THE QP PROGRAM CODE ONLY */
    AND TYPEOFASSISTANCE = 'QHCP' /* FILTERING FOR THE QHCP TYPE OF ASSISTANCE ONLY */
    AND ISHEADOFHOUSEHOLD = 'TRUE' 
    
    /*  REMOVING CODES AS PART OF NOSE 24.11 AND PREFERREDNOTIFICATIONMETHOD IN ('EE', 'ES', 'PS') */
    /* ADDING NEW PREFERENCES AS PART OF NOSE 24.11 */
    AND PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS')
    AND (
    /* ONLY SELECTS RECORDS ON THEIR INITIAL OR SECOND OR THIRD OR FOURTH NUDGE DATE */
        DATEDIFF(DAY, INITIAL_NUDGEDATE, GETDATE()) = 0 
        OR DATEDIFF(DAY, SECOND_NUDGEDATE, GETDATE()) = 0 
        OR DATEDIFF(DAY, THIRD_NUDGEDATE, GETDATE()) = 0 
        OR DATEDIFF(DAY, FOURTH_NUDGEDATE, GETDATE()) = 0
    )
    AND SVISTATUSCODE = 'PENDING' /* CHECKS THE STATUS CODE IS PENDING FOR THE JOURNEY */
    AND (
    /* FOR THIS JOURNEY, THE TASK STATUS CODE SHOULD BE  NULL OR CP(COMPLETED) */
        SEPVRFTASKSTATUS IS NULL
        OR SEPVRFTASKSTATUS = 'CP'
    )
    /* CHECKS TODAY IS ONE OR MULTIPLE DAYS BEFORE THE DUE DATE */
    AND DATEDIFF(DAY, GETDATE(), SVIDUEDATE) >= 0
    /* CHECKS TO MAKE SURE TODAY IS THE IMPORT DATE */
    AND DATEDIFF(DAY, IMPORTDATE, GETDATE()) = 0
    /* CHECKS TO SEE IF RECORD IS INSUFFICIENT */
    OR SEPISINSUFFICIENT = 'Y'