SELECT STUFF(
  (
    SELECT ',' + B.PROGRAMCODE 
    FROM [TEST_18DAY_REMINDER_STAGING] B
    WHERE F.INDIVIDUALID = B.INDIVIDUALID
    AND F.VERIFICATIONCHECKLISTDUEDATE = B.VERIFICATIONCHECKLISTDUEDATE
    FOR XML PATH('')
  ), 1, 1, '') AS PROGRAMCODE, /* CONCATENATE PROGRAM CODES */
F.CASENUMBER,	
F.FIRSTNAME,	
F.LASTNAME,	
F.EMAIL,
F.ISHEADOFHOUSEHOLD,	
F.PREFERREDCONTACTMETHODCODE,
F.VERIFICATIONCHECKLISTDUEDATE,
F.VALIDSOURCERECEIVEDDATE,	
F.INDIVIDUALID,
F.PRIMARYPHONENUMBER,	
F.LOCALE,	
F.TYPEOFASSISTANCE,
F.LANGUAGEPREFERENCE,
F.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
F.FIRST_DUEDATE_FLAG,
F.ISINSUFFICIENT,
F.DROPDOWN_COMMENTS,
F.ISEXTENDED,
F.REJECTIONDATE,
F.TODAY_DATE

FROM (SELECT A.PROGRAMCODE,
    A.CASENUMBER,	
    A.FIRSTNAME,	
    A.LASTNAME,	
    A.EMAIL,
    A.ISHEADOFHOUSEHOLD,	
    A.PREFERREDCONTACTMETHODCODE,
    A.VERIFICATIONCHECKLISTDUEDATE,
    A.VALIDSOURCERECEIVEDDATE,	
    A.INDIVIDUALID,
    A.PRIMARYPHONENUMBER,	
    A.LOCALE,	
    A.TYPEOFASSISTANCE,
    A.LANGUAGEPREFERENCE,
    A.ISINSUFFICIENT,
    A.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
    A.FIRST_DUEDATE_FLAG,
    A.DROPDOWN_COMMENTS,
    A.ISEXTENDED,
    A.REJECTIONDATE,
    A.TODAY_DATE,
    ROW_NUMBER() OVER (
        PARTITION BY A.INDIVIDUALID, A.VERIFICATIONCHECKLISTDUEDATE /* SEPERATES SENDS BY INDIVIDUAL ID AND INITIAL VERIFICATION CHECKLIST DUE DATE PER 18 DAY LOGIC */
        ORDER BY
            /* IF THERE ARE ANY IS INSUFFICIENT MARKS AS 'Y' AND THE REJECTION DATE IS TODAY WE ARE RETURNING THE LATEST REJECTIONDATE ROW (WHICH IS TODAY) TO SEND OUT THE INSUFFICIENT NUDGE*/
            CASE WHEN A.ISINSUFFICIENT = 'Y' 
            AND (A.REJECTIONDATE = A.TODAY_DATE OR A.REJECTIONDATE = DATEADD(DAY, -1, A.TODAY_DATE))
                THEN A.REJECTIONDATE
            END DESC,
            /* IF MARKED AS INSUFFICIENT BUT THE REJECTION DATE IS NOT TODAY WE ARE RETURNING ANY VALID SOURCE RECEIVED DATE IF NULL TO SEND THE 18 DAY REMINDER NUDGE */
            CASE WHEN A.ISINSUFFICIENT = 'Y' 
            AND A.REJECTIONDATE NOT IN (A.TODAY_DATE, DATEADD(DAY, -1, A.TODAY_DATE))
                THEN A.VALIDSOURCERECEIVEDDATE
            END ASC,
            /* IF THERE IS A VALID SOURCE RECEIVED DATE PRESENT WE WILL RETURN THE EARLIEST DATE (IF THERE IS ONE NULL IT WILL RETURN NULL) TO EITHER NOT SEND OUT THE 18-DAY REMINDER NUDGE OR SEND IT OUT */
            CASE WHEN A.VALIDSOURCERECEIVEDDATE IS NOT NULL 
                THEN A.VALIDSOURCERECEIVEDDATE
            END ASC,
            /* IF THERE ARE NO VALID SOURCE RECEIVED DATE PRESENT RETURN THE EARLIEST ONE (NULL) TO SEND OUT THE 18 DAY REMINDER NUDGE */
            CASE WHEN A.VALIDSOURCERECEIVEDDATE IS NULL 
                THEN A.VALIDSOURCERECEIVEDDATE
            END ASC) AS RN
    
    FROM [TEST_18DAY_REMINDER_STAGING] A
    ) AS F
/* RETURN ONLY THE FIRST ROW FOR EACH INDIVIDUAL ID AND INITIAL VERIFICATION CHECKLIST DUE DATE */
WHERE F.RN = 1