/* SELECTS STANDARD RFI AUDIENCE */
SELECT PROGRAMCODE,
CASENUMBER,	
FIRSTNAME,	
LASTNAME,	
EMAIL,
ISHEADOFHOUSEHOLD,	
PREFERREDCONTACTMETHODCODE,	
CONTACTID,
VERIFICATIONCHECKLISTDUEDATE,
VALIDSOURCERECEIVEDDATE,	
INDIVIDUALID,
IS_VERIFICATION_COMPLETED,
IS_CHECKLIST_DUE_DATE_EXPIRED,
PRIMARYPHONENUMBER,	
LOCALE,	
TYPEOFASSISTANCE,
LANGUAGEPREFERENCE,
ISINSUFFICIENT,
DROPDOWN_COMMENTS,
ISEXTENDED,
REJECTIONDATE,
FIRSTDUEDATENUDGE,
SECONDDUEDATENUDGE,
THIRDDUEDATENUDGE,
FOURTHDUEDATENUDGE,
TODAY_DATE

FROM RFI_REMINDERS_STAGING
/* SELECTS RECORDS WHERE THE DUE DATE IS TODAY OR ONE OF THE NUDGE DATES */
WHERE ((
DATEDIFF(DD, TODAY_DATE, VERIFICATIONCHECKLISTDUEDATE) = 0
OR DATEDIFF(DD, TODAY_DATE, FIRSTDUEDATENUDGE) = 0 
OR DATEDIFF(DD, TODAY_DATE, SECONDDUEDATENUDGE) = 0 
OR DATEDIFF(DD, TODAY_DATE, THIRDDUEDATENUDGE) = 0 
OR DATEDIFF(DD, TODAY_DATE, FOURTHDUEDATENUDGE) = 0
) OR ISINSUFFICIENT = 'Y')
/* SELECTS RECORDS WHERE THE DUE DATE IS NOT EXPIRED */
AND IS_CHECKLIST_DUE_DATE_EXPIRED = 0
/*SELECTED RECORDS WHERE THE VERIFICATION CHECKLIST IS NOT COMPLETED */
AND IS_VERIFICATION_COMPLETED = 0