SELECT B.CASENUMBER,
A.INDIVIDUALID,
B.PROGRAMCODE,
A.FIRSTNAME,
A.LASTNAME,
A.EMAIL,
A.PRIMARYPHONENUMBER,
A.PREFERREDNOTIFICATIONMETHOD AS PREFERREDCONTACTMETHODCODE,
'EN-US' AS LOCALE,
B.VERIFICATIONCHECKLISTDUEDATE,
B.VALIDSOURCERECEIVEDDATE,
B.TYPEOFASSISTANCE,
B.VCLDESCRIPTION,
B.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
B.VCLDESCRIPTIONES,
A.LANGUAGEPREFERENCE,
TODAY_DATE,
B.FIRST_DUEDATE_FLAG,
B.ISINSUFFICIENT,
B.DROPDOWN_COMMENTS,
B.ISEXTENDED,
B.REJECTIONDATE
/* JOINING ON HOH CONTACT DATA TABLE TO MEET THE BR OF SENDING TO HOH */
FROM TEST_IEES_CONTACT_HOH_PROD A
/* JOINING WITH THE IMPORT TABLE TO MERGE CONTACT DATA TABLE AND IMPORT RFI TABLE */
INNER JOIN [TEST_RFI_REMINDERS_PENDING_DE] B
ON A.CASENUMBER = B.CASENUMBER

WHERE 
(
B.PROGRAMCODE IN ('MA','KC','KT','CC','SN','FAD','QP') /* INCLUDING ALL RELEVANT PROGRAMS FOR 18-DAY REMINDER */
OR B.TYPEOFASSISTANCE IN ('BHP', 'APTC','ESAP') /* INCLUDING BHP, APTC, AND ESAP FOR 18-DAY REMINDER */
)
AND A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS')
/* FIRST DUE DATE FLAG = 'TRUE' SATISFIES THE 18 DAY REMINDER NUDGE BR */
/* EXISTING LOGIC FOR 18 DAY REMINDER NUDGE */
AND (
((B.FIRST_DUEDATE_FLAG = 'TRUE')
AND B.INITIAL_VERIFICATIONCHECKLISTDUEDATE IS NOT NULL) 
/* FOR ANY RFIS THAT ARE MORE THAN 8 DAYS OUT TO ACCOUNT FOR REMAINING CONTACTS NOT CONTACTED IN STANDARD RFI AUDIENCE */
/* THIS IS THE SECTION FOR THE ISINSUFFICIENT REMINDER LOGIC */
OR
(B.ISINSUFFICIENT = 'Y' )
)
/* IF VALIDSOURCERECEIVEDDATE IS NOT NULL, THEN THE RFI HAS BEEN COMPLETED */
AND VALIDSOURCERECEIVEDDATE IS NULL
AND B.VERIFICATIONCHECKLISTDUEDATE > DATEADD(DAY, 8, CAST(B.TODAY_DATE AS DATE))