SELECT C.CASENUMBER,
B.INDIVIDUALID,
C.PROGRAMCODE,
B.FIRSTNAME,
B.LASTNAME,
B.EMAIL,
B.PRIMARYPHONENUMBER,
B.PREFERREDNOTIFICATIONMETHOD AS PREFERREDCONTACTMETHODCODE,
'EN-US' AS LOCALE,
B.INDIVIDUALID AS CONTACTID,
C.VERIFICATIONCHECKLISTDUEDATE,
C.VALIDSOURCERECEIVEDDATE,
C.TYPEOFASSISTANCE,
C.VCLDESCRIPTION,
C.VCLDESCRIPTIONES,
B.LANGUAGEPREFERENCE,
C.FIRST_DUEDATE_FLAG,
C.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
C.ISINSUFFICIENT,
C.DROPDOWN_COMMENTS,
C.ISEXTENDED,
C.REJECTIONDATE,
TODAY_DATE
/* SELECTING FROM IEES HOH CONTACT TABLE BECAUSE THE BR IS TO SEND ONLY TO HOH */
FROM TEST_IEES_CONTACT_HOH_PROD B
/* JOINING WITH THE IMPORT TABLE TO MERGE CONTACT DATA TABLE AND IMPORT RFI TABLE */
INNER JOIN [TEST_RFI_REMINDERS_PENDING_DE] C
ON B.CASENUMBER = C.CASENUMBER

WHERE (
C.PROGRAMCODE IN ('MA','KC','KT','CC','SN','FAD') /* CANNOT BE OUTSIDE THESE PROGRAM CODES */
OR C.TYPEOFASSISTANCE IN ('BHP', 'APTC','ESAP') /* TYPE OF ASSISTANCE CODES */
) 
/* ENSURES THE PREFERRED NOTIFICATION METHOD IS IN THE GLOBAL_PREFERENCES TABLE */
AND B.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS')
/* THE BR CADENCE IS MEANT TO BE WITHIN 8 DAYS */
AND C.VERIFICATIONCHECKLISTDUEDATE BETWEEN CAST(C.TODAY_DATE AS DATE) AND DATEADD(DAY, 8, CAST(C.TODAY_DATE AS DATE))
/* FIRST DUE DATE FLAG IS USED FOR 18 DAY */
AND (C.FIRST_DUEDATE_FLAG = 'FALSE')