SELECT A.INDIVIDUALID AS INDIVIDUALID,
A.VERIFICATIONCHECKLISTDUEDATE AS VERIFICATIONCHECKLISTDUEDATE,
COUNT(B.VCLDESCRIPTIONES) AS VCLDESCRIPTIONES,
COUNT(B.VCLDESCRIPTION) AS VCLDESCRIPTION

FROM TEST_FINAL_RFI_REMINDERS_ENTRY_DE A

LEFT JOIN TEST_RFIS_PENDING_DE_EXLUDEVCL B 
ON A.CASENUMBER = B.CASENUMBER
AND A.VERIFICATIONCHECKLISTDUEDATE = B.VERIFICATIONCHECKLISTDUEDATE

GROUP BY
A.INDIVIDUALID,
A.VERIFICATIONCHECKLISTDUEDATE
