SELECT INDIVIDUALID,
CASENUMBER,
PROGRAMCODE,
ISHEADOFHOUSEHOLD,
CONTACTID,
VERIFICATIONCHECKLISTDUEDATE,
LOCALE,
TYPEOFASSISTANCE,
FIRST_DUEDATE_FLAG,
FIRSTDUEDATENUDGE,
SECONDDUEDATENUDGE,
THIRDDUEDATENUDGE,
FOURTHDUEDATENUDGE,
TODAY_DATE,
/* IF THERE IS A VALIDSOURCERECEIVEDDATE THEN MARKED TO VERIFICAITON COMPLETED */
CASE
    WHEN VALIDSOURCERECEIVEDDATE IS NOT NULL THEN 'TRUE'
    ELSE 'FALSE'
END AS IS_VERIFICATION_COMPLETED,
/* IF VERIFICATION CHECKLIST DUE DATE IS BEFORE TODAYS DATE THEN IT WILL BE EXPIRED*/
CASE
    WHEN VERIFICATIONCHECKLISTDUEDATE < CAST(TODAY_DATE AS DATE) THEN 'TRUE'
    ELSE 'FALSE'
  END AS IS_CHECKLIST_DUE_DATE_EXPIRED

FROM RFI_REMINDERS_STAGING