SELECT STUFF(
  (
    SELECT ',' + B.PROGRAMCODE 
    FROM [TEST_FINAL_RFI_REMINDERS_DE] B
    WHERE F.INDIVIDUALID = B.INDIVIDUALID
    AND F.VERIFICATIONCHECKLISTDUEDATE = B.VERIFICATIONCHECKLISTDUEDATE
    FOR XML PATH('')
  ), 1, 1, '') AS PROGRAMCODE, /* CONCATENATE PROGRAM CODES */
F.CASENUMBER,	
F.FIRSTNAME,	
F.LASTNAME,	
F.EMAIL,
F.ISHEADOFHOUSEHOLD,	
F.PREFERREDCONTACTMETHODCODE,	
F.CONTACTID,
F.VERIFICATIONCHECKLISTDUEDATE,
F.VALIDSOURCERECEIVEDDATE,	
F.INDIVIDUALID,
F.PRIMARYPHONENUMBER,	
F.LOCALE,	
F.TYPEOFASSISTANCE,
F.LANGUAGEPREFERENCE,
F.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
F.FIRST_DUEDATE_FLAG,
F.ISINSUFFICIENT,
F.DROPDOWN_COMMENTS,
F.ISEXTENDED,
F.REJECTIONDATE,
F.FIRSTDUEDATENUDGE,
F.SECONDDUEDATENUDGE,
F.THIRDDUEDATENUDGE,
F.FOURTHDUEDATENUDGE,
F.TODAY_DATE

FROM (SELECT A.PROGRAMCODE,
    A.CASENUMBER,	
    A.FIRSTNAME,	
    A.LASTNAME,	
    A.EMAIL,
    A.ISHEADOFHOUSEHOLD,	
    A.PREFERREDCONTACTMETHODCODE,	
    A.CONTACTID,
    A.VERIFICATIONCHECKLISTDUEDATE,
    A.VALIDSOURCERECEIVEDDATE,	
    A.INDIVIDUALID,
    A.PRIMARYPHONENUMBER,	
    A.LOCALE,	
    A.TYPEOFASSISTANCE,
    A.LANGUAGEPREFERENCE,
    A.ISINSUFFICIENT,
    A.INITIAL_VERIFICATIONCHECKLISTDUEDATE,
    A.FIRST_DUEDATE_FLAG,
    A.DROPDOWN_COMMENTS,
    A.ISEXTENDED,
    A.REJECTIONDATE,
    /* SETS NUDGE DATES EVERY OTHER DAY WITHIN THE 8 DAY RANGE */
    DATEADD(DAY, -8, A.VERIFICATIONCHECKLISTDUEDATE) AS FIRSTDUEDATENUDGE,
    DATEADD(DAY, -6, A.VERIFICATIONCHECKLISTDUEDATE) AS SECONDDUEDATENUDGE,
    DATEADD(DAY, -4, A.VERIFICATIONCHECKLISTDUEDATE) AS THIRDDUEDATENUDGE,
    DATEADD(DAY, -2, A.VERIFICATIONCHECKLISTDUEDATE) AS FOURTHDUEDATENUDGE,
    A.TODAY_DATE,
    ROW_NUMBER() OVER (
        PARTITION BY A.INDIVIDUALID, A.VERIFICATIONCHECKLISTDUEDATE /* SEPERATES SENDS BY INDIVIDUAL ID AND VERIFICATION CHECKLIST DUE DATE */
        ORDER BY
            /* IF MARKED AS INSUFFICIENT WITHIN 24 HOURS OF TODAY RETURN REJECTION DATE */
            CASE 
                WHEN A.ISINSUFFICIENT = 'Y'
                AND (A.REJECTIONDATE = A.TODAY_DATE OR A.REJECTIONDATE = DATEADD(DAY, -1, A.TODAY_DATE))
                    THEN A.REJECTIONDATE
            END DESC,
            /* IF MARKED AS INSUFFICIENT BUT NOT WITHIN 24 HOURS RETURN VALID SOURCE RECEIVED DATE */
            CASE 
                WHEN A.ISINSUFFICIENT = 'Y' 
                AND A.REJECTIONDATE NOT IN (A.TODAY_DATE, DATEADD(DAY, -1, A.TODAY_DATE))
                    THEN A.VALIDSOURCERECEIVEDDATE
            END ASC,
            /* IF ALL STANDARD RFI HAS BEEN FILLED OUT RETURN VALID SOURCE RECEIVED DATE */
            CASE 
                WHEN A.VALIDSOURCERECEIVEDDATE IS NOT NULL 
                    THEN A.VALIDSOURCERECEIVEDDATE
            END ASC,
            /* IF ALL STANDARD RFI HAS NOT BEEN FILLED OUT RETURN VALID SOURCE RECEIVED DATE */
            CASE
                WHEN A.VALIDSOURCERECEIVEDDATE IS NULL 
                    THEN A.VALIDSOURCERECEIVEDDATE
            END ASC) AS RN
    
    FROM [TEST_FINAL_RFI_REMINDERS_DE] A
    ) AS F
/* RETURN ONLY THE FIRST ROW FOR EACH INDIVIDUAL ID AND VERIFICATION CHECKLIST DUE DATE */
WHERE F.RN = 1