SELECT VALIDSOURCERECEIVEDDATE, 
TYPEOFASSISTANCE,
/* WE ARE UPDATING THE INITIAL VERIFICATION CHECKLIST DUE DATE WITH ANY NEW DUE DATE AS IEES DOES NOT FOR EXTENDED CASES AND FOR EMPTY CASES */
CASE WHEN ISEXTENDED = 'Y'
OR INITIAL_VERIFICATIONCHECKLISTDUEDATE IS NULL
    THEN DATEADD(DAY, -15, VERIFICATIONCHECKLISTDUEDATE)
    ELSE INITIAL_VERIFICATIONCHECKLISTDUEDATE
END AS INITIAL_VERIFICATIONCHECKLISTDUEDATE,
/* UPDATE THE FIRST DUE DATE FLAG FOR ANY THAT ARE 18 DAYS OUT TODAY AND EXTENDED OR DID NOT HAVE DATA */
CASE WHEN CAST(TODAY_DATE AS DATE) = DATEADD(DAY, -18, VERIFICATIONCHECKLISTDUEDATE)
AND (ISEXTENDED = 'Y'
OR INITIAL_VERIFICATIONCHECKLISTDUEDATE IS NULL)
    THEN 1
    ELSE FIRST_DUEDATE_FLAG
END AS FIRST_DUEDATE_FLAG,
ISINSUFFICIENT,
DROPDOWN_COMMENTS,
ISEXTENDED,
REJECTIONDATE,
/* CASTING THIS AS A DATE WITH NO TIME FOR THE RFI LOGIC */
CAST(TODAY_DATE AS DATE) AS TODAY_DATE,
VCLDESCRIPTIONES,
VCLDESCRIPTION,
PROGRAMCODE,
CASENUMBER,
VERIFICATIONCHECKLISTDUEDATE

/* FROM THE IMPORT TABLE */
FROM TEST_RFI_REMINDERS_IMPORT_DE