SELECT B.INDIVIDUALID,
B.CASENUMBER,
B.PROGRAMCODE,
B.ISHEADOFHOUSEHOLD,
B.CONTACTID,
B.VERIFICATIONCHECKLISTDUEDATE,
B.IS_VERIFICATION_COMPLETED,
B.IS_CHECKLIST_DUE_DATE_EXPIRED,
B.DATEADDEDTOTHEJOURNEY,
B.LOCALE,
B.TYPEOFASSISTANCE,
B.FIRSTDUEDATENUDGE,
B.SECONDDUEDATENUDGE,
B.THIRDDUEDATENUDGE,
B.FOURTHDUEDATENUDGE,
B.TODAY_DATE,
A.VCLDESCRIPTIONES AS COUNT_VCLDESCRIPTIONES,
A.VCLDESCRIPTION AS COUNT_VCLDESCRIPTION

FROM TEST_VCLDESCRIPTION_LOGIC_DE A

INNER JOIN TEST_FINAL_RFI_REMINDERS_ENTRY_DE B ON
A.INDIVIDUALID = B.INDIVIDUALID AND
A.VERIFICATIONCHECKLISTDUEDATE = B.VERIFICATIONCHECKLISTDUEDATE
