SELECT A.VERIFICATIONCHECKLISTDUEDATE,
A.VALIDSOURCERECEIVEDDATE,
A.VCLDESCRIPTIONES,
A.VCLDESCRIPTION,
A.PROGRAMCODE,
A.CASENUMBER,
A.TYPEOFASSISTANCE

FROM TEST_FINAL_RFIS_PENDING_DE A
/* EXCLUDES RECORDS WITH THE FOLLOWING VCL DESCRIPTION */
WHERE VCLDESCRIPTION != 'YOU NEED TO COMPLETE YOUR INTERVIEW' 
AND VCLDESCRIPTION != 'VERIFICATION OF AUTH REP'
/* EXCLUDES ANY RECORDS THAT ARE NOT INCLUDED IN THE FINAL JOURNEY ENTRY DE TABLE */ 
AND CASENUMBER IN (SELECT CASENUMBER
    FROM TEST_FINAL_RFI_REMINDERS_ENTRY_DE)