SELECT
 CASENUMBER,
 PROGRAMCODE,
 RENEWALTYPECODE,	
 REVIEWSTATUSCODE,
 REVIEWDUEDATE,
 EDGNUMBER,
 CASESTATUSCODE,
 EMAIL,
 FIRSTNAME,
 LASTNAME,
 PREFERREDNOTIFICATIONMETHOD,
 PRIMARYPHONENUMBER,
 LANGUAGEPREFERENCE,
 ISPRIMARYTEXTPREFERRED,
 INDIVIDUALID,
 LOCALE,
 CONTACTID,
 DATEADDEDTOJOURNEY,
 TYPEOFASSISTANCE,
 CASEPROGRAMSTATUSCODE,
 EXITNUDGENUMBER,
 EXITCREATEDDATE,
 SKYENROLLED,
 MCOENROLLED
 
 FROM
    (SELECT
    CASENUMBER,
    PROGRAMCODE,
    RENEWALTYPECODE,	
    REVIEWSTATUSCODE,
    REVIEWDUEDATE,
    EDGNUMBER,
    CASESTATUSCODE,
    EMAIL,
    FIRSTNAME,
    LASTNAME,
    PREFERREDNOTIFICATIONMETHOD,
    PRIMARYPHONENUMBER,
    LANGUAGEPREFERENCE,
    ISPRIMARYTEXTPREFERRED,
    INDIVIDUALID,
    LOCALE,
    CONTACTID,
    DATEADDEDTOJOURNEY,
    TYPEOFASSISTANCE,
    CASEPROGRAMSTATUSCODE,
    EXITNUDGENUMBER,
    EXITCREATEDDATE,
    SKYENROLLED,
    MCOENROLLED,
    ROW_NUMBER() OVER (
    PARTITION BY CONTACTID
    ORDER BY DATEADDEDTOJOURNEY DESC) AS RANK
    FROM
    [MEDICAID_BENEFITS_EXPIRATION_ENTRY] ) T
 
 WHERE RANK = 1
 
 
 /* **IMPORTANT** ANY CHANGES TO DE LATEST_MEIDCAD_APPEND_DE_V1 WILL REQUIRE CHANGES IN MA ALTERNATE COVERAGE QUERY AS WELL */