/*  CURRENTLYINMEDICAIDUPDATE_ENTRYDE_NOI-JL
    MEDICAID_BENEFITS_EXPIRATION_REVIEW_ENTRY */
SELECT 
A.PROGRAMCODE,
A.CASENUMBER,
A.RENEWALTYPECODE,
A.REVIEWSTATUSCODE,
A.REVIEWDUEDATE,
A.EDGNUMBER,
A.CASESTATUSCODE,
B.EMAIL,
B.FIRSTNAME,
B.INDIVIDUALID,
B.INDIVIDUALID AS CONTACTID,
B.LASTNAME,
B.PREFERREDNOTIFICATIONMETHOD,
CASE
    WHEN LEN(B.PRIMARYPHONENUMBER) >= 10 THEN CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(B.PRIMARYPHONENUMBER),'-',''),'(',''),')',''),' ',''),10))
    ELSE NULL
END AS PRIMARYPHONENUMBER,
B.LANGUAGEPREFERENCE,
A.TYPEOFASSISTANCE,
'EN-US' AS LOCALE

FROM TEST_IEES_CONTACT_HOH_PROD B

INNER JOIN [TEST_IEES_CASE] A  ON
B.CASENUMBER = A.CASENUMBER

WHERE 
A.RENEWALTYPECODE ='AC'
AND A.PROGRAMCODE = 'MA' 
AND A.TYPEOFASSISTANCE != 'APTC'
AND (A.REVIEWSTATUSCODE='RR' OR A.REVIEWSTATUSCODE='RI')

/* UPDATED AS A PART OF NOSE 24.11 AND B.PREFERREDNOTIFICATIONMETHOD IN ('EE','ES','PS') */
AND B.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS') 
AND DATEDIFF(DAY,CAST(GETDATE() AS DATE),A.REVIEWDUEDATE) BETWEEN -9 AND 65

/* **IMPORTANT** ANY CHANGES TO DE CURRENTLYINMEDICAIDUPDATE_ENTRYDE_NOI-JL WILL REQUIRE CHANGES IN MA ALTERNATE COVERAGE QUERY AS WELL */
