/*  MEDICAIDUPDATE_ENTRYDE_NOI-JL 
    MEDICAID_BENEFITS_EXPIRATION_ENTRY */
SELECT 
A.PROGRAMCODE,
A.CASENUMBER,
A.RENEWALTYPECODE,
A.REVIEWSTATUSCODE,
A.REVIEWDUEDATE,
A.EDGNUMBER,
A.CASESTATUSCODE,
B.EMAIL,
B.FIRSTNAME,
B.INDIVIDUALID,
B.INDIVIDUALID AS CONTACTID,
B.LASTNAME,
B.PREFERREDNOTIFICATIONMETHOD,
CASE
    WHEN LEN(B.PRIMARYPHONENUMBER) >= 10 THEN CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(B.PRIMARYPHONENUMBER),'-',''),'(',''),')',''),' ',''),10))
    ELSE NULL
END AS PRIMARYPHONENUMBER,
B.LANGUAGEPREFERENCE,
A.TYPEOFASSISTANCE,
'EN-US' AS LOCALE,
SKY_FLAG AS SKYENROLLED,
MCO_ENROLLED AS MCOENROLLED

FROM TEST_IEES_CONTACT_HOH_PROD B

INNER JOIN [TEST_IEES_CASE] A  ON
B.CASENUMBER = A.CASENUMBER

WHERE 
A.RENEWALTYPECODE ='AC'
AND A.ISACTIVE = 'Y'
AND A.PROGRAMCODE = 'MA' 
AND A.TYPEOFASSISTANCE != 'APTC'
AND A.REVIEWSTATUSCODE='RR'

/* UPDATED AS A PART OF NOSE AND B.PREFERREDNOTIFICATIONMETHOD IN ('EE','ES','PS') */
AND B.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS') 

AND DATEDIFF(DAY,CAST(GETDATE() AS DATE),A.REVIEWDUEDATE) BETWEEN 0 AND 65
