SELECT INDIVIDUALID,
PROGRAMCODE,
CASENUMBER,
FIRSTNAME,
LASTNAME,
EMAIL,
CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(PRIMARYPHONENUMBER),'-',''),'(',''),')',''),' ',''),10)) AS PRIMARYPHONENUMBER,
LANGUAGEPREFERENCE,
PREFERREDNOTIFICATIONMETHOD,
ISHEADOFHOUSEHOLD,
CHILDCARESELECTED,
APPROVALDATE,
NUDGED_DATE_70_DAYS

FROM CCAP_ENROLLMENTS_IMPORT

WHERE 
    (APPROVALDATE = CAST(GETDATE() AS DATE) OR NUDGED_DATE_70_DAYS = CAST(GETDATE() AS DATE))
    AND CHILDCARESELECTED = 'No'
    AND ISHEADOFHOUSEHOLD = 'Yes'