SELECT Q1.*
FROM
  ( SELECT A.EMAIL AS EMAILADDRESS,
           A.FIRSTNAME AS FIRSTNAME,
           A.PRIMARYPHONENUMBER AS PHONE,
           /*CASE
               WHEN A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_ONLY') THEN 0
               WHEN A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS_PAPERSMS') THEN 1
                UPDATED AS PART OF NOSE 24.11 ^WAS: 
                WHEN A.PREFERREDNOTIFICATIONMETHOD = 'EE' THEN 0
                WHEN A.PREFERREDNOTIFICATIONMETHOD IN ('ES','PS') THEN 1
               ELSE 0
           END AS SMSOPTIN,*/
           CASE
               WHEN A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS_PAPERSMS') THEN 1
                ELSE 0
                END AS SMSOPTIN,
           CASE
               WHEN A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'OPTIN_EMAIL_SMS') THEN 1
               /* UPDATED AS PART OF NOSE 24.11 ^WAS: 
                WHEN A.PREFERREDNOTIFICATIONMETHOD IN ('EE','ES') THEN 1
               */
               ELSE 0
           END AS EMAILOPTIN,
           A.INDIVIDUALID AS CONTACTID,
           CASE
               WHEN A.LANGUAGEPREFERENCE = 'SPANISH' THEN 1
               ELSE 0
           END AS OPTEDFORSPANISH,
           CASE
               WHEN A.PREFERREDNOTIFICATIONMETHOD IS NULL THEN 1
               ELSE 0
           END AS UNSUBSCRIBE,
           ROW_NUMBER() OVER (PARTITION BY A.INDIVIDUALID
                              ORDER BY A.INDIVIDUALID) AS ROW
   FROM ALTERNATE_COVERAGE_PHASE3_ENTRY A ) Q1
WHERE Q1.ROW = 1