/*  DISCONTINUE REASONS ARE TURNED INTO AN ARRAY AND GROUPED TO ADDRESS POSSIBLE DUPLICATES.
    ALTERNATE_COVERAGE_PHASE3_ENTRY */
SELECT STUFF(
       ( SELECT ',' + B.DISCONTINUEREASON
        FROM [ALTERNATE_COVERAGE_PHASE3_STAGING] B
        WHERE A.INDIVIDUALID = B.INDIVIDUALID
          FOR XML PATH('') ), 1, 1, '') AS DISCONTINUEREASON,
       A.FIRSTNAME,
       A.PROGRAMCODE,
       A.CASENUMBER,
       A.REVIEWDUEDATE,
       A.PRIMARYPHONENUMBER,
       A.EMAIL,
       A.INDIVIDUALID,
       A.HEADOFHOUSEHOLD,
       A.LANGUAGEPREFERENCE,
       A.CASEPROGRAMSTATUSCODE,
       A.PREFERREDNOTIFICATIONMETHOD,
       A.CREATEDDATE,
       A.LOCALE,
       A.UPDATEDDATE,
       A.EXITNUDGENUMBER,
       A.TYPEOFASSISTANCE
FROM [ALTERNATE_COVERAGE_PHASE3_STAGING] A
WHERE A.HEADOFHOUSEHOLD = 'Y'
AND A.PROGRAMCODE = 'MA'
AND A.CASEPROGRAMSTATUSCODE ='DC'
GROUP BY A.FIRSTNAME,
         A.PROGRAMCODE,
         A.CASENUMBER,
         A.REVIEWDUEDATE,
         A.PRIMARYPHONENUMBER,
         A.EMAIL,
         A.INDIVIDUALID,
         A.HEADOFHOUSEHOLD,
         A.LANGUAGEPREFERENCE,
         A.CASEPROGRAMSTATUSCODE,
         A.PREFERREDNOTIFICATIONMETHOD,
         A.CREATEDDATE,
         A.LOCALE,
         A.UPDATEDDATE,
         A.EXITNUDGENUMBER,
         A.TYPEOFASSISTANCE
