/* PULLS RECORDS FROM PHE IMPORT DATA EXTENSION WITH A MATCHING INDID AND CASE NUMBER IN MEDICAID JOURNEY */
SELECT 
TOP 1
A.FIRSTNAME AS FIRSTNAME,
A.PROGRAMCODE AS PROGRAMCODE,
A.CASENUMBER AS CASENUMBER,
A.REVIEWDUEDATE AS REVIEWDUEDATE,
CASE
    WHEN LEN(A.PRIMARYPHONENUMBER) >= 10 THEN CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(A.PRIMARYPHONENUMBER),'-',''),'(',''),')',''),' ',''),10))
    ELSE NULL
END AS PRIMARYPHONENUMBER,
A.EMAIL AS EMAIL,
A.INDIVIDUALID AS INDIVIDUALID,
A.HEADOFHOUSEHOLD AS HEADOFHOUSEHOLD,
A.[LANGUAGE PREFERENCE] AS LANGUAGEPREFERENCE,
A.CASEPROGRAMSTATUSCODE AS CASEPROGRAMSTATUSCODE,
A.PREFERREDNOTIFICATIONMETHOD AS PREFERREDNOTIFICATIONMETHOD,
A.[DISCONTINUE REASON] AS DISCONTINUEREASON,
A.[CREATED DATE] AS CREATEDDATE,
'EN-US' AS LOCALE,
A.[UPDATED DATE] AS UPDATEDDATE,
CASE
  WHEN B.EXITNUDGENUMBER IS NULL THEN C.REVIEWSTATUSCODE
  ELSE B.EXITNUDGENUMBER
END AS EXITNUDGENUMBER,
B.TYPEOFASSISTANCE

FROM [90DAY_PHASE2_IMPORT] A

LEFT JOIN [LATEST_MEIDCAD_APPEND_DE_V1] B ON A.INDIVIDUALID = B.INDIVIDUALID /* MAYBE CHANGE */
AND A.CASENUMBER = B.CASENUMBER
LEFT JOIN [CURRENTLYINMEDICAIDUPDATE_ENTRYDE_NOI-JL] C ON A.INDIVIDUALID = C.INDIVIDUALID /* MAYBE CHANGE */
AND A.CASENUMBER = C.CASENUMBER
WHERE UPPER(A.HEADOFHOUSEHOLD) = 'Y'
  AND A.PROGRAMCODE = 'MA'
  AND A.CASEPROGRAMSTATUSCODE ='DC'
  AND (B.TYPEOFASSISTANCE != 'SSIR'
       OR B.TYPEOFASSISTANCE IS NULL)
  AND A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD = 'EMAIL_SMS')