-- SELECT THE AUTOMATION CUSTOMER KEY, AUTOMATION NAME, AND THE COUNT OF RUNS
SELECT AI.AUTOMATIONCUSTOMERKEY,
    AI.AUTOMATIONNAME AS AUTOMATIONNAME,
    COUNT(*) AS RUNCOUNT

-- FROM THE _AUTOMATIONINSTANCE TABLE
FROM _AUTOMATIONINSTANCE AI

-- FILTER RECORDS WHERE THE AUTOMATION INSTANCE START TIME IS WITHIN THE LAST DAY
WHERE AI.AUTOMATIONINSTANCESTARTTIME_UTC >= DATEADD(DAY, -1, CAST(GETDATE() AS DATE))

-- GROUP THE RESULTS BY AUTOMATION NAME AND CUSTOMER KEY
GROUP BY AI.AUTOMATIONNAME,
AI.AUTOMATIONNAME,
AI.AUTOMATIONCUSTOMERKEY