SELECT 
    AI.AUTOMATIONCUSTOMERKEY,
    AI.AUTOMATIONNAME AS AUTOMATIONNAME,
    COUNT(*) AS RUNCOUNT

FROM _AUTOMATIONINSTANCE AI

WHERE AI.AUTOMATIONINSTANCESTARTTIME_UTC >= DATEADD(DAY, -21, CAST(GETDATE() AS DATE))

GROUP BY ROLLUP (AI.AUTOMATIONCUSTOMERKEY, AI.AUTOMATIONNAME)
