SELECT SUBSCRIBERKEY

FROM ALL_CONTACTS_MIRROR_DE

WHERE SUBSCRIBERKEY NOT LIKE '%@%'
    AND NOT (SUBSCRIBERKEY LIKE '003%')
    AND NOT (SUBSCRIBERKEY LIKE '005%')
    AND NOT (LEN(SUBSCRIBERKEY) = 7 AND LEFT(SUBSCRIBERKEY, 1) = 'U')
    AND NOT (LEN(SUBSCRIBERKEY) = 7)
    AND NOT (LEN(SUBSCRIBERKEY) = 8 AND SUBSCRIBERKEY NOT LIKE '%[^0-9]%')
    AND NOT (LEN(SUBSCRIBERKEY) = 9 AND LEFT(SUBSCRIBERKEY, 1) = '1' AND SUBSCRIBERKEY NOT LIKE '%[^0-9]%')
    AND NOT (SUBSCRIBERKEY LIKE '%-%' AND LEN(SUBSCRIBERKEY) = 36)