SELECT CONCAT(CASENUMBER, '|', PROGRAMCODE) AS SUBSCRIBERKEY,
'VCLDESCRIPTIONES' AS INVALIDFIELD,
VCLDESCRIPTIONES AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM DATAEXTENSION
WHERE VCLDESCRIPTIONES IS NULL

UNION ALL

SELECT CONCAT(CASENUMBER, '|', PROGRAMCODE) AS SUBSCRIBERKEY,
'VCLDESCRIPTIONES' AS INVALIDFIELD,
VCLDESCRIPTIONES AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM DATAEXTENSION
WHERE LEN(VCLDESCRIPTIONES) > 250

UNION ALL

SELECT CONCAT(CASENUMBER, '|', PROGRAMCODE) AS SUBSCRIBERKEY,
'VCLDESCRIPTION' AS INVALIDFIELD,
VCLDESCRIPTION AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM DATAEXTENSION
WHERE VCLDESCRIPTION IS NULL

UNION ALL

SELECT CONCAT(CASENUMBER, '|', PROGRAMCODE) AS SUBSCRIBERKEY,
'VCLDESCRIPTION' AS INVALIDFIELD,
VCLDESCRIPTION AS INVALIDVALUE,
'LEN CHECK' AS VALIDATIONTYPE
FROM DATAEXTENSION
WHERE LEN(VCLDESCRIPTION) > 250

UNION ALL

SELECT CONCAT(CASENUMBER, '|', PROGRAMCODE) AS SUBSCRIBERKEY,
'TYPEOFASSISTANCE' AS INVALIDFIELD,
TYPEOFASSISTANCE AS INVALIDVALUE,
'NULL CHECK' AS VALIDATIONTYPE
FROM DATAEXTENSION
WHERE TYPEOFASSISTANCE IS NULL
