SELECT 
    SENDDATE,
    AVG(TOTALEMAILSSENT) AS DAILY_AVG,
    STDEV(TOTALEMAILSSENT) AS DAILY_STDDEV,
    AVG(TOTALEMAILSSENT) + 2 * STDEV(TOTALEMAILSSENT) AS LIMIT
FROM (
    SELECT 
        CONVERT(DATE, S.EVENTDATE) AS SENDDATE,
        COUNT(*) AS TOTALEMAILSSENT
    FROM _SENT S
    JOIN _JOB J ON S.JOBID = J.JOBID
    WHERE 
        CAST(S.EVENTDATE AS TIME) BETWEEN '07:30:00' AND '08:30:00'
        AND4 S.EVENTDATE >= DATEADD(MONTH, -1, GETDATE())
        AND S.EVENTDATE < GETDATE()
    GROUP BY 
        CONVERT(DATE, S.EVENTDATE)
) AS DailySends
GROUP BY SENDDATE
ORDER BY SENDDATE
