/*  FIRST QUERY
    90DAY_PHASE2_STAGING */

SELECT 
A.FIRSTNAME AS FIRSTNAME, 
A.PROGRAMCODE AS PROGRAMCODE, 
A.CASENUMBER AS CASENUMBER, 
A.REVIEWDUEDATE AS REVIEWDUEDATE,
CASE
    WHEN Len(A.PRIMARYPHONENUMBER) >= 10 THEN CONCAT('1',RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(Trim(A.PRIMARYPHONENUMBER),'-',''),'(',''),')',''),' ',''),10))
    ELSE NULL
END AS PRIMARYPHONENUMBER,
A.EMAIL AS EMAIL,
A.INDIVIDUALID AS INDIVIDUALID, 
A.INDIVIDUALID AS CONTACTID,
A.HEADOFHOUSEHOLD AS HEADOFHOUSEHOLD, 
A.[LANGUAGE PREFERENCE] AS LANGUAGEPREFERENCE, 
A.CASEPROGRAMSTATUSCODE AS CASEPROGRAMSTATUSCODE, 
A.PREFERREDNOTIFICATIONMETHOD AS PREFERREDNOTIFICATIONMETHOD,
A.[DISCONTINUE REASON] AS DISCONTINUEREASON , 
A.[CREATED DATE] AS CREATEDDATE, 
A.[UPDATED DATE] AS UPDATEDDATE, 
'EN-US' AS LOCALE, 
A.[MAILING ADDRESS] AS MAILINGADDRESS,
B.LASTLOGINDATE
FROM [90DAY_PHASE2_IMPORT] A
LEFT JOIN [USER_SALESFORCE_1_V2] B /* CHANGE IN CUTOVER */
	ON A.EMAIL = B.EMAIL
WHERE A.PROGRAMCODE = 'MA'
AND A.HEADOFHOUSEHOLD = 'Y' 
AND CONVERT(DATE,A.REVIEWDUEDATE) = CONVERT(DATE,DATEADD(D, 90, GETDATE())) 
AND A.PREFERREDNOTIFICATIONMETHOD IN (SELECT VALUE FROM GLOBAL_PREFERENCES WHERE KEYWORD ='EMAIL_SMS')
AND A.REVIEWDUEDATE < '2025-08-01' /*UPDATED AS A PART OF CR 2153 24.11 */
